### PR TITLE
GET-33 | scaffold project according to model

### PR DESCRIPTION
**Pull request by 0tuedon**
Renamed the Previous branch [here](https://github.com/getnshare/frontend/pull/9) to this and edited the title

### CODE REVIEW

**Review by Lord-sarcastic — CHANGES_REQUESTED** [review]
Take a look again at the guidelines on creating PRs and rework this PR title. We will not move forward without it.

**Review by Lord-sarcastic — CHANGES_REQUESTED** [review]
I can't find a `utils` folder in your structure. Secondly, we do not have an `app.css` file.

Also, why is there a CSS file in the assets folder?

**Comment by 0tuedon** [comment]
> I can't find a `utils` folder in your structure. Secondly, we do not have an `app.css` file.
> 
> Also, why is there a CSS file in the assets folder?
> 
> Your commit messages do not follow the convention stated in the contributions module. Please fix that using this link [here](https://www.google.com/url?sa=t&source=web&rct=j&url=https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message%23:~:text%3DOn%2520the%2520command%2520line%252C%2520navigate,message%252C%2520and%2520save%2520the%2520commit.&ved=2ahUKEwim1JOMjLH1AhVlEWMBHfkwACAQFnoECAQQBQ&usg=AOvVaw2IehST63fX-wrMc2NA46Ht)

The document does not talk about editing commit message on github or does it automatically sync

**Review by Lord-sarcastic — CHANGES_REQUESTED** [review]
Remove previous commit histories

**Pull request closed without merging**
